/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hpe.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Actor service. Represents a row in the &quot;HPE_Actor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hpe.service.model.impl.ActorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hpe.service.model.impl.ActorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Actor
 * @generated
 */
@ProviderType
public interface ActorModel extends BaseModel<Actor> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a actor model instance should use the {@link Actor} interface instead.
	 */

	/**
	 * Returns the primary key of this actor.
	 *
	 * @return the primary key of this actor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this actor.
	 *
	 * @param primaryKey the primary key of this actor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this actor.
	 *
	 * @return the uuid of this actor
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this actor.
	 *
	 * @param uuid the uuid of this actor
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the actor ID of this actor.
	 *
	 * @return the actor ID of this actor
	 */
	public long getActorId();

	/**
	 * Sets the actor ID of this actor.
	 *
	 * @param actorId the actor ID of this actor
	 */
	public void setActorId(long actorId);

	/**
	 * Returns the actor name of this actor.
	 *
	 * @return the actor name of this actor
	 */
	@AutoEscape
	public String getActorName();

	/**
	 * Sets the actor name of this actor.
	 *
	 * @param actorName the actor name of this actor
	 */
	public void setActorName(String actorName);

	/**
	 * Returns the age of this actor.
	 *
	 * @return the age of this actor
	 */
	public int getAge();

	/**
	 * Sets the age of this actor.
	 *
	 * @param age the age of this actor
	 */
	public void setAge(int age);

	/**
	 * Returns the languages of this actor.
	 *
	 * @return the languages of this actor
	 */
	@AutoEscape
	public String getLanguages();

	/**
	 * Sets the languages of this actor.
	 *
	 * @param languages the languages of this actor
	 */
	public void setLanguages(String languages);

	/**
	 * Returns the movies of this actor.
	 *
	 * @return the movies of this actor
	 */
	@AutoEscape
	public String getMovies();

	/**
	 * Sets the movies of this actor.
	 *
	 * @param movies the movies of this actor
	 */
	public void setMovies(String movies);

	/**
	 * Returns the critic rating of this actor.
	 *
	 * @return the critic rating of this actor
	 */
	public int getCriticRating();

	/**
	 * Sets the critic rating of this actor.
	 *
	 * @param criticRating the critic rating of this actor
	 */
	public void setCriticRating(int criticRating);

}